before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install freebsd-buildutils bmake; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; brew install bsdmake; fi
script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then bmake; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then bsdmake; fi
os:
  - linux
  - osx
language: c
compiler:
  - clang
  - gcc
